### PR TITLE
Handle 'swarm org add-user' where user has no access to the org

### LINKED ISSUE #349: Tried to add a user to a non-existing org raises internal server error
```
Kallisto:~ zeisss$ swarm org create wub-verlag
Organization 'wub-verlag' has been created
Kallisto:~ zeisss$ swarm org add-user org neofonie
Unknown server error: error-id: NX0CZ/41zGP

Please try again in a moment. If the problem remains, please contact us at support@giantswarm.io.
Kallisto:~ zeisss$ swarm org add-user wub-verlag neofonie
User 'neofonie' has been added to organization 'wub-verlag'
```

### PR DESCRIPTION
**Pull request by marians**
Fixes #349

Example:

```
$ swarm org add-user org blahblah
The organization 'org' does not exist or you do not have access to it. Please double-check the name.
```

Also contains a little cleanup of the examples in the help:

```
Manage organizations

Usage: 
  swarm org [flags]

Docs:
  https://docs.giantswarm.io/reference/cli/org/

Examples:
  swarm org -l                                 List organizations the user has access to
  swarm org create <organization>              Create new organization
  swarm org delete <organization>              Delete the given organization
  swarm org show <organization>                Print the members of the given organization
  swarm org add-user <organization> <user>     Add the given user to the given organization
  swarm org remove-user <organization> <user>  Remove the given user from the given organization

Flags:
  -l, --list[=false]: List all organizations the current user has access to
  -y, --yes[=false]: Assume yes on all confirmations
...
```

### CODE REVIEW

**Comment by marians** [comment]
RFR @ewoutp @zeisss

File: org.go [hunk 1]
```diff
@@ -169,6 +169,8 @@ func cmdOrganizationAddMember(organization, user string) {
 			Quitf("User '%s' is already a member of organization '%s'.\n", user, organization)
 		} else if clientgo.IsUserNotFound(err) {
 			Quitf("User '%s' does not exist.\n", user)
+		} else if clientgo.IsForbidden(err) {
+			Quitf("The organization '%s' does not exist or you are not a member of it. Please double-check the name.\n", organization)
```
Comment (ewoutp) [inline org.go]: This text is currently correct, but I can imagine that we'll add more fine grained access control in the future.
Should we prepare for that with a text like "...or you have not been granted access to it..."

**Comment by ewoutp** [comment]
Minor text suggestions
Do the int-tests needs updating?

Code LGTM

File: org.go [hunk 2]
```diff
@@ -32,11 +32,11 @@ var (
 		Short: "Manage organizations",
 		Long:  "Manage organizations",
 		Example: strings.Join([]string{
-			"create <organization>                 Create new organization",
-			"delete -y <organization>              Delete the given organization. Use -y to assume yes on confirmations",
-			"show <organization>                   Print the members of the given organization",
-			"add-user <organization> <username>    Add the given user to the given organization",
-			"remove-user <organization> <username> Remove the given user from the given organization",
+			"swarm create <organization>                 Create new organization",
+			"swarm delete <organization>                 Delete the given organization",
```
Comment (zeisss) [inline org.go]: why did we drop the `[-y]` flag here?

File: org.go (hunk 1 above)
Comment (marians) [inline org.go]: Will do. Actually thought about it, but didn't do it yet.

File: org.go (hunk 2 above)
Comment (marians) [inline org.go]: Because it's not necessary to have every possible flag in an example.

The examples should give a general idea of how the command can be used. They shouldn't become too big.

The flags are explained in a different part of the help output anyway.

**Comment by marians** [comment]
While fixing the cram test, I found that the examples in usage were broken, so I fixed theses and tweaked them a bit more. Should be all fine now.

**Comment by ewoutp** [comment]
LGTM
